[build]
  publish = "frontend/build"
  command = "cd frontend && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://your-app-name.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", X-Requested-With = "*", Accept = "*", Content-Type = "application/json"}

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://your-app-name.onrender.com"
  REACT_APP_DOMAIN = "creditcarbon.netlify.app"
  REACT_APP_SITE_NAME = "CREDIT CARBON"
  NODE_ENV = "production"
  API_VERSION = "v1"
