services:
  - type: web
    name: carboncredits-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python3 -m uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://creditcarbon:TMZteSf7yxqCv0i9@cluster0.xxxxx.mongodb.net/carbon_credit
      - key: JWT_SECRET
        generateValue: true
      - key: DB_NAME
        value: carbon_credit
      - key: CORS_ORIGINS
        value: https://creditcarbon.netlify.app,https://credit-carbon.netlify.app
