services:
  - type: web
    name: carboncredits-backend
    env: python
    buildCommand: "echo 'Building minimal FastAPI server'"
    startCommand: "python3 -c \"
from fastapi import FastAPI
import uvicorn

app = FastAPI()

@app.get('/')
def root():
    return {'message': 'API is running'}

@app.get('/health')
def health():
    return {'status': 'ok'}

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=10000)
\""
    envVars:
      - key: PORT
        value: 10000
