services:
  - type: web
    name: carboncredits-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python3 -m uvicorn backend.server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        generateValue: true
      - key: MONGO_URL
        value: "mongodb+srv://navpreet2257_db_user:TMZteSf7yxqCv0i9@cluster0.lfjm5r2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: DB_NAME
        value: "carbon_credit"
      - key: JWT_SECRET
        value: "9k2J8nP5qR3tY6wE1zX4cV7bN0mL3hG5jK8pQ2rT4yW6uA9sD1fG3hJ5k"
      - key: CORS_ORIGINS
        value: "https://creditcarbon.netlify.app,https://credit-carbon.netlify.app"
